[window]
Title = "ProtoPlat"
Width = 1280
Height = 720
TargetFPS = 75

[[input.actions]]
Name = "MoveLeft"
KeyboardKeys = [65, 263]
MouseButtons = []
MultiKey = false

[[input.actions]]
Name = "MoveRight"
KeyboardKeys = [68, 262]
MouseButtons = []
MultiKey = false

[[input.actions]]
Name = "InteractUI"
KeyboardKeys = []
MouseButtons = [0]
MultiKey = false
